// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/bigquery/datatransfer/v1/datasource.proto

package com.google.cloud.bigquery.datatransfer.v1;

public interface GetCredentialsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.datatransfer.v1.GetCredentialsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Name of this credentials object in the form
   * projects/-/locations/{location_id}/dataSources/{data_source_id}/credentials/{user_id}
   * </pre>
   *
   * <code>string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * Name of this credentials object in the form
   * projects/-/locations/{location_id}/dataSources/{data_source_id}/credentials/{user_id}
   * </pre>
   *
   * <code>string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
