// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/bigquery/datatransfer/v1/resourcestate.proto

package com.google.cloud.bigquery.datatransfer.v1;

public final class ResourceStateProto {
  private ResourceStateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9google/cloud/bigquery/datatransfer/v1/" +
      "resourcestate.proto\022%google.cloud.bigque" +
      "ry.datatransfer.v1\032\037google/protobuf/time" +
      "stamp.protoB\344\001\n)com.google.cloud.bigquer" +
      "y.datatransfer.v1B\022ResourceStateProtoP\001Z" +
      "Qgoogle.golang.org/genproto/googleapis/c" +
      "loud/bigquery/datatransfer/v1;datatransf" +
      "er\252\002%Google.Cloud.BigQuery.DataTransfer." +
      "V1\312\002%Google\\Cloud\\BigQuery\\DataTransfer\\" +
      "V1b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
