// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/bigquery/datatransfer/v1/datatransfer.proto

package com.google.cloud.bigquery.datatransfer.v1;

public final class DataTransferProto {
  private DataTransferProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_bigquery_datatransfer_v1_DataSourceParameter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_bigquery_datatransfer_v1_DataSourceParameter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_bigquery_datatransfer_v1_DataSource_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_bigquery_datatransfer_v1_DataSource_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_bigquery_datatransfer_v1_GetDataSourceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_bigquery_datatransfer_v1_GetDataSourceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_bigquery_datatransfer_v1_ListDataSourcesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_bigquery_datatransfer_v1_ListDataSourcesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_bigquery_datatransfer_v1_ListDataSourcesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_bigquery_datatransfer_v1_ListDataSourcesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_bigquery_datatransfer_v1_CreateTransferConfigRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_bigquery_datatransfer_v1_CreateTransferConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_bigquery_datatransfer_v1_UpdateTransferConfigRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_bigquery_datatransfer_v1_UpdateTransferConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_bigquery_datatransfer_v1_GetTransferConfigRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_bigquery_datatransfer_v1_GetTransferConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_bigquery_datatransfer_v1_DeleteTransferConfigRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_bigquery_datatransfer_v1_DeleteTransferConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_bigquery_datatransfer_v1_GetTransferRunRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_bigquery_datatransfer_v1_GetTransferRunRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_bigquery_datatransfer_v1_DeleteTransferRunRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_bigquery_datatransfer_v1_DeleteTransferRunRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferConfigsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferConfigsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferConfigsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferConfigsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferRunsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferRunsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferRunsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferRunsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferLogsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferLogsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferLogsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferLogsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_bigquery_datatransfer_v1_CheckValidCredsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_bigquery_datatransfer_v1_CheckValidCredsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_bigquery_datatransfer_v1_CheckValidCredsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_bigquery_datatransfer_v1_CheckValidCredsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_bigquery_datatransfer_v1_ScheduleTransferRunsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_bigquery_datatransfer_v1_ScheduleTransferRunsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_bigquery_datatransfer_v1_ScheduleTransferRunsRequest_LabelsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_bigquery_datatransfer_v1_ScheduleTransferRunsRequest_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_bigquery_datatransfer_v1_ScheduleTransferRunsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_bigquery_datatransfer_v1_ScheduleTransferRunsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_bigquery_datatransfer_v1_EnableDataTransferServiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_bigquery_datatransfer_v1_EnableDataTransferServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_bigquery_datatransfer_v1_IsDataTransferServiceEnabledRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_bigquery_datatransfer_v1_IsDataTransferServiceEnabledRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_bigquery_datatransfer_v1_IsDataTransferServiceEnabledResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_bigquery_datatransfer_v1_IsDataTransferServiceEnabledResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n8google/cloud/bigquery/datatransfer/v1/" +
      "datatransfer.proto\022%google.cloud.bigquer" +
      "y.datatransfer.v1\032\034google/api/annotation" +
      "s.proto\0324google/cloud/bigquery/datatrans" +
      "fer/v1/transfer.proto\032\036google/protobuf/d" +
      "uration.proto\032\033google/protobuf/empty.pro" +
      "to\032 google/protobuf/field_mask.proto\032\037go" +
      "ogle/protobuf/timestamp.proto\032\036google/pr" +
      "otobuf/wrappers.proto\"\361\004\n\023DataSourcePara" +
      "meter\022\020\n\010param_id\030\001 \001(\t\022\024\n\014display_name\030" +
      "\002 \001(\t\022\023\n\013description\030\003 \001(\t\022M\n\004type\030\004 \001(\016" +
      "2?.google.cloud.bigquery.datatransfer.v1" +
      ".DataSourceParameter.Type\022\020\n\010required\030\005 " +
      "\001(\010\022\020\n\010repeated\030\006 \001(\010\022\030\n\020validation_rege" +
      "x\030\007 \001(\t\022\026\n\016allowed_values\030\010 \003(\t\022/\n\tmin_v" +
      "alue\030\t \001(\0132\034.google.protobuf.DoubleValue" +
      "\022/\n\tmax_value\030\n \001(\0132\034.google.protobuf.Do" +
      "ubleValue\022J\n\006fields\030\013 \003(\0132:.google.cloud" +
      ".bigquery.datatransfer.v1.DataSourcePara" +
      "meter\022\036\n\026validation_description\030\014 \001(\t\022\033\n" +
      "\023validation_help_url\030\r \001(\t\022\021\n\timmutable\030" +
      "\016 \001(\010\022\017\n\007recurse\030\017 \001(\010\"i\n\004Type\022\024\n\020TYPE_U" +
      "NSPECIFIED\020\000\022\n\n\006STRING\020\001\022\013\n\007INTEGER\020\002\022\n\n" +
      "\006DOUBLE\020\003\022\013\n\007BOOLEAN\020\004\022\n\n\006RECORD\020\005\022\r\n\tPL" +
      "US_PAGE\020\006\"\211\010\n\nDataSource\022\014\n\004name\030\001 \001(\t\022\026" +
      "\n\016data_source_id\030\002 \001(\t\022\024\n\014display_name\030\003" +
      " \001(\t\022\023\n\013description\030\004 \001(\t\022\021\n\tclient_id\030\005" +
      " \001(\t\022\016\n\006scopes\030\006 \003(\t\022N\n\rtransfer_type\030\007 " +
      "\001(\01623.google.cloud.bigquery.datatransfer" +
      ".v1.TransferTypeB\002\030\001\022\'\n\033supports_multipl" +
      "e_transfers\030\010 \001(\010B\002\030\001\022\037\n\027update_deadline" +
      "_seconds\030\t \001(\005\022\030\n\020default_schedule\030\n \001(\t" +
      "\022 \n\030supports_custom_schedule\030\013 \001(\010\022N\n\npa" +
      "rameters\030\014 \003(\0132:.google.cloud.bigquery.d" +
      "atatransfer.v1.DataSourceParameter\022\020\n\010he" +
      "lp_url\030\r \001(\t\022_\n\022authorization_type\030\016 \001(\016" +
      "2C.google.cloud.bigquery.datatransfer.v1" +
      ".DataSource.AuthorizationType\022\\\n\021data_re" +
      "fresh_type\030\017 \001(\0162A.google.cloud.bigquery" +
      ".datatransfer.v1.DataSource.DataRefreshT" +
      "ype\022(\n default_data_refresh_window_days\030" +
      "\020 \001(\005\022\034\n\024manual_runs_disabled\030\021 \001(\010\022<\n\031m" +
      "inimum_schedule_interval\030\022 \001(\0132\031.google." +
      "protobuf.Duration\022\032\n\022partner_legal_name\030" +
      "\026 \001(\t\022\024\n\014redirect_url\030\027 \001(\t\"s\n\021Authoriza" +
      "tionType\022\"\n\036AUTHORIZATION_TYPE_UNSPECIFI" +
      "ED\020\000\022\026\n\022AUTHORIZATION_CODE\020\001\022\"\n\036GOOGLE_P" +
      "LUS_AUTHORIZATION_CODE\020\002\"c\n\017DataRefreshT" +
      "ype\022!\n\035DATA_REFRESH_TYPE_UNSPECIFIED\020\000\022\022" +
      "\n\016SLIDING_WINDOW\020\001\022\031\n\025CUSTOM_SLIDING_WIN" +
      "DOW\020\002\"$\n\024GetDataSourceRequest\022\014\n\004name\030\001 " +
      "\001(\t\"O\n\026ListDataSourcesRequest\022\016\n\006parent\030" +
      "\001 \001(\t\022\022\n\npage_token\030\003 \001(\t\022\021\n\tpage_size\030\004" +
      " \001(\005\"{\n\027ListDataSourcesResponse\022G\n\014data_" +
      "sources\030\001 \003(\01321.google.cloud.bigquery.da" +
      "tatransfer.v1.DataSource\022\027\n\017next_page_to" +
      "ken\030\002 \001(\t\"\231\001\n\033CreateTransferConfigReques" +
      "t\022\016\n\006parent\030\001 \001(\t\022N\n\017transfer_config\030\002 \001" +
      "(\01325.google.cloud.bigquery.datatransfer." +
      "v1.TransferConfig\022\032\n\022authorization_code\030" +
      "\003 \001(\t\"\272\001\n\033UpdateTransferConfigRequest\022N\n" +
      "\017transfer_config\030\001 \001(\01325.google.cloud.bi" +
      "gquery.datatransfer.v1.TransferConfig\022\032\n" +
      "\022authorization_code\030\003 \001(\t\022/\n\013update_mask" +
      "\030\004 \001(\0132\032.google.protobuf.FieldMask\"(\n\030Ge" +
      "tTransferConfigRequest\022\014\n\004name\030\001 \001(\t\"+\n\033" +
      "DeleteTransferConfigRequest\022\014\n\004name\030\001 \001(" +
      "\t\"%\n\025GetTransferRunRequest\022\014\n\004name\030\001 \001(\t" +
      "\"(\n\030DeleteTransferRunRequest\022\014\n\004name\030\001 \001" +
      "(\t\"l\n\032ListTransferConfigsRequest\022\016\n\006pare" +
      "nt\030\001 \001(\t\022\027\n\017data_source_ids\030\002 \003(\t\022\022\n\npag" +
      "e_token\030\003 \001(\t\022\021\n\tpage_size\030\004 \001(\005\"\207\001\n\033Lis" +
      "tTransferConfigsResponse\022O\n\020transfer_con" +
      "figs\030\001 \003(\01325.google.cloud.bigquery.datat" +
      "ransfer.v1.TransferConfig\022\027\n\017next_page_t" +
      "oken\030\002 \001(\t\"\255\002\n\027ListTransferRunsRequest\022\016" +
      "\n\006parent\030\001 \001(\t\022D\n\006states\030\002 \003(\01624.google." +
      "cloud.bigquery.datatransfer.v1.TransferS" +
      "tate\022\022\n\npage_token\030\003 \001(\t\022\021\n\tpage_size\030\004 " +
      "\001(\005\022^\n\013run_attempt\030\005 \001(\0162I.google.cloud." +
      "bigquery.datatransfer.v1.ListTransferRun" +
      "sRequest.RunAttempt\"5\n\nRunAttempt\022\033\n\027RUN" +
      "_ATTEMPT_UNSPECIFIED\020\000\022\n\n\006LATEST\020\001\"~\n\030Li" +
      "stTransferRunsResponse\022I\n\rtransfer_runs\030" +
      "\001 \003(\01322.google.cloud.bigquery.datatransf" +
      "er.v1.TransferRun\022\027\n\017next_page_token\030\002 \001" +
      "(\t\"\257\001\n\027ListTransferLogsRequest\022\016\n\006parent" +
      "\030\001 \001(\t\022\022\n\npage_token\030\004 \001(\t\022\021\n\tpage_size\030" +
      "\005 \001(\005\022]\n\rmessage_types\030\006 \003(\0162F.google.cl" +
      "oud.bigquery.datatransfer.v1.TransferMes" +
      "sage.MessageSeverity\"\206\001\n\030ListTransferLog" +
      "sResponse\022Q\n\021transfer_messages\030\001 \003(\01326.g" +
      "oogle.cloud.bigquery.datatransfer.v1.Tra" +
      "nsferMessage\022\027\n\017next_page_token\030\002 \001(\t\"&\n" +
      "\026CheckValidCredsRequest\022\014\n\004name\030\001 \001(\t\"2\n" +
      "\027CheckValidCredsResponse\022\027\n\017has_valid_cr" +
      "eds\030\001 \001(\010\"\232\002\n\033ScheduleTransferRunsReques" +
      "t\022\016\n\006parent\030\001 \001(\t\022^\n\006labels\030\006 \003(\0132N.goog" +
      "le.cloud.bigquery.datatransfer.v1.Schedu" +
      "leTransferRunsRequest.LabelsEntry\022.\n\nsta" +
      "rt_time\030\002 \001(\0132\032.google.protobuf.Timestam" +
      "p\022,\n\010end_time\030\003 \001(\0132\032.google.protobuf.Ti" +
      "mestamp\032-\n\013LabelsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005v" +
      "alue\030\002 \001(\t:\0028\001\"`\n\034ScheduleTransferRunsRe" +
      "sponse\022@\n\004runs\030\001 \003(\01322.google.cloud.bigq" +
      "uery.datatransfer.v1.TransferRun\"0\n Enab" +
      "leDataTransferServiceRequest\022\014\n\004name\030\001 \001" +
      "(\t\"3\n#IsDataTransferServiceEnabledReques" +
      "t\022\014\n\004name\030\001 \001(\t\"G\n$IsDataTransferService" +
      "EnabledResponse\022\017\n\007enabled\030\001 \001(\010\022\016\n\006reas" +
      "on\030\002 \001(\t2\370\036\n\023DataTransferService\022\337\001\n\rGet" +
      "DataSource\022;.google.cloud.bigquery.datat" +
      "ransfer.v1.GetDataSourceRequest\0321.google" +
      ".cloud.bigquery.datatransfer.v1.DataSour" +
      "ce\"^\202\323\344\223\002X\022//v1/{name=projects/*/locatio" +
      "ns/*/dataSources/*}Z%\022#/v1/{name=project" +
      "s/*/dataSources/*}\022\360\001\n\017ListDataSources\022=" +
      ".google.cloud.bigquery.datatransfer.v1.L" +
      "istDataSourcesRequest\032>.google.cloud.big" +
      "query.datatransfer.v1.ListDataSourcesRes" +
      "ponse\"^\202\323\344\223\002X\022//v1/{parent=projects/*/lo" +
      "cations/*}/dataSourcesZ%\022#/v1/{parent=pr" +
      "ojects/*}/dataSources\022\235\002\n\024CreateTransfer" +
      "Config\022B.google.cloud.bigquery.datatrans" +
      "fer.v1.CreateTransferConfigRequest\0325.goo" +
      "gle.cloud.bigquery.datatransfer.v1.Trans" +
      "ferConfig\"\211\001\202\323\344\223\002\202\001\"3/v1/{parent=project" +
      "s/*/locations/*}/transferConfigs:\017transf" +
      "er_configZ:\"\'/v1/{parent=projects/*}/tra" +
      "nsferConfigs:\017transfer_config\022\275\002\n\024Update" +
      "TransferConfig\022B.google.cloud.bigquery.d" +
      "atatransfer.v1.UpdateTransferConfigReque" +
      "st\0325.google.cloud.bigquery.datatransfer." +
      "v1.TransferConfig\"\251\001\202\323\344\223\002\242\0012C/v1/{transf" +
      "er_config.name=projects/*/locations/*/tr" +
      "ansferConfigs/*}:\017transfer_configZJ27/v1" +
      "/{transfer_config.name=projects/*/transf" +
      "erConfigs/*}:\017transfer_config\022\332\001\n\024Delete" +
      "TransferConfig\022B.google.cloud.bigquery.d" +
      "atatransfer.v1.DeleteTransferConfigReque" +
      "st\032\026.google.protobuf.Empty\"f\202\323\344\223\002`*3/v1/" +
      "{name=projects/*/locations/*/transferCon" +
      "figs/*}Z)*\'/v1/{name=projects/*/transfer" +
      "Configs/*}\022\363\001\n\021GetTransferConfig\022?.googl" +
      "e.cloud.bigquery.datatransfer.v1.GetTran" +
      "sferConfigRequest\0325.google.cloud.bigquer" +
      "y.datatransfer.v1.TransferConfig\"f\202\323\344\223\002`" +
      "\0223/v1/{name=projects/*/locations/*/trans" +
      "ferConfigs/*}Z)\022\'/v1/{name=projects/*/tr" +
      "ansferConfigs/*}\022\204\002\n\023ListTransferConfigs" +
      "\022A.google.cloud.bigquery.datatransfer.v1" +
      ".ListTransferConfigsRequest\032B.google.clo" +
      "ud.bigquery.datatransfer.v1.ListTransfer" +
      "ConfigsResponse\"f\202\323\344\223\002`\0223/v1/{parent=pro" +
      "jects/*/locations/*}/transferConfigsZ)\022\'" +
      "/v1/{parent=projects/*}/transferConfigs\022" +
      "\255\002\n\024ScheduleTransferRuns\022B.google.cloud." +
      "bigquery.datatransfer.v1.ScheduleTransfe" +
      "rRunsRequest\032C.google.cloud.bigquery.dat" +
      "atransfer.v1.ScheduleTransferRunsRespons" +
      "e\"\213\001\202\323\344\223\002\204\001\"B/v1/{parent=projects/*/loca" +
      "tions/*/transferConfigs/*}:scheduleRuns:" +
      "\001*Z;\"6/v1/{parent=projects/*/transferCon" +
      "figs/*}:scheduleRuns:\001*\022\370\001\n\016GetTransferR" +
      "un\022<.google.cloud.bigquery.datatransfer." +
      "v1.GetTransferRunRequest\0322.google.cloud." +
      "bigquery.datatransfer.v1.TransferRun\"t\202\323" +
      "\344\223\002n\022:/v1/{name=projects/*/locations/*/t" +
      "ransferConfigs/*/runs/*}Z0\022./v1/{name=pr" +
      "ojects/*/transferConfigs/*/runs/*}\022\342\001\n\021D" +
      "eleteTransferRun\022?.google.cloud.bigquery" +
      ".datatransfer.v1.DeleteTransferRunReques" +
      "t\032\026.google.protobuf.Empty\"t\202\323\344\223\002n*:/v1/{" +
      "name=projects/*/locations/*/transferConf" +
      "igs/*/runs/*}Z0*./v1/{name=projects/*/tr" +
      "ansferConfigs/*/runs/*}\022\211\002\n\020ListTransfer" +
      "Runs\022>.google.cloud.bigquery.datatransfe" +
      "r.v1.ListTransferRunsRequest\032?.google.cl" +
      "oud.bigquery.datatransfer.v1.ListTransfe" +
      "rRunsResponse\"t\202\323\344\223\002n\022:/v1/{parent=proje" +
      "cts/*/locations/*/transferConfigs/*}/run" +
      "sZ0\022./v1/{parent=projects/*/transferConf" +
      "igs/*}/runs\022\251\002\n\020ListTransferLogs\022>.googl" +
      "e.cloud.bigquery.datatransfer.v1.ListTra" +
      "nsferLogsRequest\032?.google.cloud.bigquery" +
      ".datatransfer.v1.ListTransferLogsRespons" +
      "e\"\223\001\202\323\344\223\002\214\001\022I/v1/{parent=projects/*/loca" +
      "tions/*/transferConfigs/*/runs/*}/transf" +
      "erLogsZ?\022=/v1/{parent=projects/*/transfe" +
      "rConfigs/*/runs/*}/transferLogs\022\227\002\n\017Chec" +
      "kValidCreds\022=.google.cloud.bigquery.data" +
      "transfer.v1.CheckValidCredsRequest\032>.goo" +
      "gle.cloud.bigquery.datatransfer.v1.Check" +
      "ValidCredsResponse\"\204\001\202\323\344\223\002~\"?/v1/{name=p" +
      "rojects/*/locations/*/dataSources/*}:che" +
      "ckValidCreds:\001*Z8\"3/v1/{name=projects/*/" +
      "dataSources/*}:checkValidCreds:\001*\022\304\001\n\031En" +
      "ableDataTransferService\022G.google.cloud.b" +
      "igquery.datatransfer.v1.EnableDataTransf" +
      "erServiceRequest\032\026.google.protobuf.Empty" +
      "\"F\202\323\344\223\002@\";/v1/{name=projects/*/locations" +
      "/*}:enableDataTransferService:\001*\022\250\002\n\034IsD" +
      "ataTransferServiceEnabled\022J.google.cloud" +
      ".bigquery.datatransfer.v1.IsDataTransfer" +
      "ServiceEnabledRequest\032K.google.cloud.big" +
      "query.datatransfer.v1.IsDataTransferServ" +
      "iceEnabledResponse\"o\202\323\344\223\002i\">/v1/{name=pr" +
      "ojects/*/locations/*}:isDataTransferServ" +
      "iceEnabled:\001*Z$\"\037/v1/{name=projects/*}:i" +
      "sEnabled:\001*B\343\001\n)com.google.cloud.bigquer" +
      "y.datatransfer.v1B\021DataTransferProtoP\001ZQ" +
      "google.golang.org/genproto/googleapis/cl" +
      "oud/bigquery/datatransfer/v1;datatransfe" +
      "r\252\002%Google.Cloud.BigQuery.DataTransfer.V" +
      "1\312\002%Google\\Cloud\\BigQuery\\DataTransfer\\V" +
      "1b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.cloud.bigquery.datatransfer.v1.TransferProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.FieldMaskProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        }, assigner);
    internal_static_google_cloud_bigquery_datatransfer_v1_DataSourceParameter_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_bigquery_datatransfer_v1_DataSourceParameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_bigquery_datatransfer_v1_DataSourceParameter_descriptor,
        new java.lang.String[] { "ParamId", "DisplayName", "Description", "Type", "Required", "Repeated", "ValidationRegex", "AllowedValues", "MinValue", "MaxValue", "Fields", "ValidationDescription", "ValidationHelpUrl", "Immutable", "Recurse", });
    internal_static_google_cloud_bigquery_datatransfer_v1_DataSource_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_bigquery_datatransfer_v1_DataSource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_bigquery_datatransfer_v1_DataSource_descriptor,
        new java.lang.String[] { "Name", "DataSourceId", "DisplayName", "Description", "ClientId", "Scopes", "TransferType", "SupportsMultipleTransfers", "UpdateDeadlineSeconds", "DefaultSchedule", "SupportsCustomSchedule", "Parameters", "HelpUrl", "AuthorizationType", "DataRefreshType", "DefaultDataRefreshWindowDays", "ManualRunsDisabled", "MinimumScheduleInterval", "PartnerLegalName", "RedirectUrl", });
    internal_static_google_cloud_bigquery_datatransfer_v1_GetDataSourceRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_bigquery_datatransfer_v1_GetDataSourceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_bigquery_datatransfer_v1_GetDataSourceRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_cloud_bigquery_datatransfer_v1_ListDataSourcesRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_bigquery_datatransfer_v1_ListDataSourcesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_bigquery_datatransfer_v1_ListDataSourcesRequest_descriptor,
        new java.lang.String[] { "Parent", "PageToken", "PageSize", });
    internal_static_google_cloud_bigquery_datatransfer_v1_ListDataSourcesResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_bigquery_datatransfer_v1_ListDataSourcesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_bigquery_datatransfer_v1_ListDataSourcesResponse_descriptor,
        new java.lang.String[] { "DataSources", "NextPageToken", });
    internal_static_google_cloud_bigquery_datatransfer_v1_CreateTransferConfigRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_bigquery_datatransfer_v1_CreateTransferConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_bigquery_datatransfer_v1_CreateTransferConfigRequest_descriptor,
        new java.lang.String[] { "Parent", "TransferConfig", "AuthorizationCode", });
    internal_static_google_cloud_bigquery_datatransfer_v1_UpdateTransferConfigRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_cloud_bigquery_datatransfer_v1_UpdateTransferConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_bigquery_datatransfer_v1_UpdateTransferConfigRequest_descriptor,
        new java.lang.String[] { "TransferConfig", "AuthorizationCode", "UpdateMask", });
    internal_static_google_cloud_bigquery_datatransfer_v1_GetTransferConfigRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_google_cloud_bigquery_datatransfer_v1_GetTransferConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_bigquery_datatransfer_v1_GetTransferConfigRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_cloud_bigquery_datatransfer_v1_DeleteTransferConfigRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_google_cloud_bigquery_datatransfer_v1_DeleteTransferConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_bigquery_datatransfer_v1_DeleteTransferConfigRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_cloud_bigquery_datatransfer_v1_GetTransferRunRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_google_cloud_bigquery_datatransfer_v1_GetTransferRunRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_bigquery_datatransfer_v1_GetTransferRunRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_cloud_bigquery_datatransfer_v1_DeleteTransferRunRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_google_cloud_bigquery_datatransfer_v1_DeleteTransferRunRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_bigquery_datatransfer_v1_DeleteTransferRunRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferConfigsRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferConfigsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferConfigsRequest_descriptor,
        new java.lang.String[] { "Parent", "DataSourceIds", "PageToken", "PageSize", });
    internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferConfigsResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferConfigsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferConfigsResponse_descriptor,
        new java.lang.String[] { "TransferConfigs", "NextPageToken", });
    internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferRunsRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferRunsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferRunsRequest_descriptor,
        new java.lang.String[] { "Parent", "States", "PageToken", "PageSize", "RunAttempt", });
    internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferRunsResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferRunsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferRunsResponse_descriptor,
        new java.lang.String[] { "TransferRuns", "NextPageToken", });
    internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferLogsRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferLogsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferLogsRequest_descriptor,
        new java.lang.String[] { "Parent", "PageToken", "PageSize", "MessageTypes", });
    internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferLogsResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferLogsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_bigquery_datatransfer_v1_ListTransferLogsResponse_descriptor,
        new java.lang.String[] { "TransferMessages", "NextPageToken", });
    internal_static_google_cloud_bigquery_datatransfer_v1_CheckValidCredsRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_google_cloud_bigquery_datatransfer_v1_CheckValidCredsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_bigquery_datatransfer_v1_CheckValidCredsRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_cloud_bigquery_datatransfer_v1_CheckValidCredsResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_google_cloud_bigquery_datatransfer_v1_CheckValidCredsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_bigquery_datatransfer_v1_CheckValidCredsResponse_descriptor,
        new java.lang.String[] { "HasValidCreds", });
    internal_static_google_cloud_bigquery_datatransfer_v1_ScheduleTransferRunsRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_google_cloud_bigquery_datatransfer_v1_ScheduleTransferRunsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_bigquery_datatransfer_v1_ScheduleTransferRunsRequest_descriptor,
        new java.lang.String[] { "Parent", "Labels", "StartTime", "EndTime", });
    internal_static_google_cloud_bigquery_datatransfer_v1_ScheduleTransferRunsRequest_LabelsEntry_descriptor =
      internal_static_google_cloud_bigquery_datatransfer_v1_ScheduleTransferRunsRequest_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_bigquery_datatransfer_v1_ScheduleTransferRunsRequest_LabelsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_bigquery_datatransfer_v1_ScheduleTransferRunsRequest_LabelsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_cloud_bigquery_datatransfer_v1_ScheduleTransferRunsResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_google_cloud_bigquery_datatransfer_v1_ScheduleTransferRunsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_bigquery_datatransfer_v1_ScheduleTransferRunsResponse_descriptor,
        new java.lang.String[] { "Runs", });
    internal_static_google_cloud_bigquery_datatransfer_v1_EnableDataTransferServiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_google_cloud_bigquery_datatransfer_v1_EnableDataTransferServiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_bigquery_datatransfer_v1_EnableDataTransferServiceRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_cloud_bigquery_datatransfer_v1_IsDataTransferServiceEnabledRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_google_cloud_bigquery_datatransfer_v1_IsDataTransferServiceEnabledRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_bigquery_datatransfer_v1_IsDataTransferServiceEnabledRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_cloud_bigquery_datatransfer_v1_IsDataTransferServiceEnabledResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_google_cloud_bigquery_datatransfer_v1_IsDataTransferServiceEnabledResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_bigquery_datatransfer_v1_IsDataTransferServiceEnabledResponse_descriptor,
        new java.lang.String[] { "Enabled", "Reason", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.cloud.bigquery.datatransfer.v1.TransferProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.FieldMaskProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
